FROM node:16-alpine
USER root
RUN mkdir -p /usr/app && chown -R node:node /usr/app
USER node
RUN mkdir -p /usr/app
WORKDIR /usr/app
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
CMD [ "npm", "run", "dev" ]
